/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScoreEntry = IDL.Record({
  'id' : IDL.Nat,
  'waveReached' : IDL.Nat,
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
  'playerName' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearScores' : IDL.Func([], [], []),
  'getPlayerScores' : IDL.Func([IDL.Text], [IDL.Vec(ScoreEntry)], ['query']),
  'getTopScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
  'submitScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScoreEntry = IDL.Record({
    'id' : IDL.Nat,
    'waveReached' : IDL.Nat,
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
    'playerName' : IDL.Text,
  });
  
  return IDL.Service({
    'clearScores' : IDL.Func([], [], []),
    'getPlayerScores' : IDL.Func([IDL.Text], [IDL.Vec(ScoreEntry)], ['query']),
    'getTopScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
    'submitScore' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };